build.gradle
src/main/java/project/domain/cart/Cart.java
src/main/java/project/domain/cartitem/CartItem.java
src/main/java/project/domain/category/Category.java
src/main/java/project/domain/common/BaseEntity.java
src/main/java/project/domain/item/Item.java
src/main/java/project/domain/itemimage/ItemImage.java
src/main/java/project/domain/purchasehistory/PurchaseHistory.java
src/main/java/project/domain/review/Review.java
src/main/java/project/domain/store/Store.java
src/main/java/project/domain/subcategory/SubCategory.java
src/main/java/project/domain/user/Gender.java
src/main/java/project/domain/user/Language.java
src/main/java/project/domain/user/PersonalType.java
src/main/java/project/domain/user/Role.java
src/main/java/project/domain/user/SkinType.java
src/main/java/project/domain/user/User.java
src/main/java/project/domain/wishlist/WishList.java

Base code와, Entity를 구현했습니다.
Resolves: #3
>
```java
```
> 
> 
>

[FS2-14-FEAT-3] : Base code, Entity 구현

---

build.gradle
src/main/java/project/domain/cart/Cart.java
src/main/java/project/domain/item/Item.java
src/main/java/project/domain/itemimage/ItemImage.java
src/main/java/project/domain/purchasehistory/PurchaseHistory.java
src/main/java/project/domain/review/Review.java
src/main/java/project/global/config/SwaggerConfig.java

Swagger api 연동했습니다.
Resolves: #5
>
```java
```
> 
> 
>

[FEAT-5]  Swagger api 연동했습니다.

---

src/main/java/project/global/config/SwaggerConfig.java
src/main/java/project/global/config/WebMvcConfig.java

1. SwaggerConfig에 authorization 기능 추가헸습니다.
2. LoginArgumentResolver를 등록했습니다.
Resolves: #14
>
```java
```
> 
> 
>

[FIX-14] Swgger api, 로그인 관련 기능 수정

---

build.gradle
src/main/java/project/domain/cart/Cart.java
src/main/java/project/domain/cart/controller/CartController.java
src/main/java/project/domain/cart/dto/CartConverter.java
src/main/java/project/domain/cart/dto/CartRequest.java
src/main/java/project/domain/cart/dto/CartResponse.java
src/main/java/project/domain/cart/repository/CartRepository.java
src/main/java/project/domain/cart/service/CartService.java
src/main/java/project/domain/cartitem/CartItem.java
src/main/java/project/domain/cartitem/repository/CartItemRepository.java
src/main/java/project/domain/item/Item.java
src/main/java/project/domain/item/repository/ItemRepository.java
src/main/java/project/domain/member/Member.java
src/main/java/project/domain/member/repository/MemberRepository.java
src/main/java/project/domain/member/service/MemberService.java
src/main/java/project/domain/purchasehistory/PurchaseHistory.java
src/main/java/project/domain/review/Review.java
src/main/java/project/domain/wishlist/WishList.java
src/main/java/project/global/config/SwaggerConfig.java
src/main/java/project/global/response/status/ErrorStatus.java
src/main/java/project/global/security/util/JwtUtil.java

1. 장바구니 상품 조회/등록/수량 추가/삭제 기능 구현
2. 결제 창으로 넘어가는 QR 코드 이미지 생성 후 클라이언트에게 전달하는 기능 구현
3. 추가로 필요한 에러 코드 추가
4. 구현된 기능 Swagger API docs 설명 추가
Resolves: #11 
>
> 1. 장바구니 조회
> ![image](https://github.com/user-attachments/assets/b5690e4d-77d1-420f-aba0-c60485b64eaa)
> 2. 장바구니 상품 등록
> ![image](https://github.com/user-attachments/assets/dda57b92-04e3-45b1-8397-2e100c249d1b)
> ![image](https://github.com/user-attachments/assets/b35b01f6-13b3-4c3a-8ea1-01b4d05fcb86)
> 3. 장바구니 상품 수량 +1
> ![image](https://github.com/user-attachments/assets/69d7a66b-ca1e-4a5d-be12-d3c6dc7bd0fb)
> ![image](https://github.com/user-attachments/assets/d1ea1fad-f71d-439a-832f-2aa56358e444)
> 4. 장바구니 상품 수량 -1
> …

[FS2-27 FEAT-11] :  장바구니 기능 구현

---

src/main/java/project/domain/mbti/MbtiQuestion.java
src/main/java/project/domain/mbti/SkinAxis.java
src/main/java/project/domain/mbti/Step.java
src/main/java/project/domain/mbti/controller/MbtiQuestionController.java
src/main/java/project/domain/mbti/dto/MbtiQuestionConverter.java
src/main/java/project/domain/mbti/dto/MbtiQuestionRequest.java
src/main/java/project/domain/mbti/dto/MbtiQuestionResponse.java
src/main/java/project/domain/mbti/repository/MbtiQuestionRepository.java
src/main/java/project/domain/mbti/service/MbtiQuestionService.java
src/main/java/project/global/response/status/ErrorStatus.java

1. 축에 관해 질문리스트를 뽑아서 조회합니다.
>
> ### SkinType Enum class 추가 
```java
@Getter
@RequiredArgsConstructor
public enum SkinAxis {
PIGMENT("색소"),     // 색소축
MOISTURE("수분/유분"),    // 수분/유분 축
REACTIVITY("반응성");   // 반응성 축
private final String string;
public static SkinAxis getSkinAxis(String axis) {
return Arrays.stream(SkinAxis.values())
.filter(axis1 -> axis1.string.equals(axis))
.findFirst()
.orElse(null);
}
}
```
>
>
>  ### Step Enum class 추가 
```java
public enum Step {
START,
MIDDLE,
E,
B,
F,
S,
A,
W;
public static Boolean checkEnd(Step step) {
return step != START && step != MIDDLE;
}
}
```
> -**질문에 해당하는 위치를 알수있도록 Step Enum class를 생성했습니다.**
>  질문의 시작 => START
> 질문 진행중 => MIDDLE
> 질문의 끝 => 각 MBTI의 유형 
>
>
> ### MbtiQuestion Entity를 생성했습니다.
```java
package project.domain.mbti;
import …
```

[FEAT-21] 피부 설문조사에 관한 기능 추가

---

src/main/java/project/domain/purchasehistory/PurchaseHistory.java
src/main/java/project/domain/purchasehistory/controller/PurchaseHistoryController.java
src/main/java/project/domain/purchasehistory/dto/PurchaseHistoryConverter.java
src/main/java/project/domain/purchasehistory/dto/PurchaseHistoryResponse.java
src/main/java/project/domain/purchasehistory/repository/PurchaseHistoryRepository.java
src/main/java/project/domain/purchasehistory/service/PurchaseHistoryService.java

1. 구매내역 전체 조회 기능을 추가했습니다.
2. 구매내역 상세 조회 기능을 추가했습니다.
>
> 
> **PurchaseHistoryResponse 를 추가했습니다.**
```java
public abstract class PurchaseHistoryResponse {
@Builder
@Getter
@AllArgsConstructor
@NoArgsConstructor
public static class DateInfoListDTO{
private LocalDate date;
private List<String> imgUrlList;
}
@Builder
@Getter
@AllArgsConstructor
@NoArgsConstructor
public static class InfoListDTO{
private List<DateInfoListDTO> dateInfoList;
}
@Builder
@Getter
@AllArgsConstructor
@NoArgsConstructor
public static class DetailInfoListDTO{
private List<DetailInfoDTO> detailInfoList;
private Integer totalPrice;
}
@Builder
@Getter
@AllArgsConstructor
@NoArgsConstructor
public static class DetailInfoDTO{
private Long itemId;
private String itemName;
private String imgUrl; …
```

[FEAT-19] : 구매내역 관련 기능 추가

---

build.gradle
src/main/java/project/domain/common/BaseEntity.java
src/main/java/project/domain/review/Review.java
src/main/java/project/domain/review/controller/ReviewController.java
src/main/java/project/domain/review/dto/ReviewConverter.java
src/main/java/project/domain/review/dto/ReviewRequest.java
src/main/java/project/domain/review/dto/ReviewResponse.java
src/main/java/project/domain/review/repository/ReviewRepository.java
src/main/java/project/domain/review/service/ReviewService.java
src/main/java/project/domain/reviewimage/ReviewImage.java
src/main/java/project/domain/reviewimage/repository/ReviewImageRepository.java
src/main/java/project/domain/wishlist/controller/WishListController.java
src/main/java/project/domain/wishlist/dto/WishListConverter.java
src/main/java/project/domain/wishlist/dto/WishListResponse.java
src/main/java/project/domain/wishlist/service/WishListService.java
src/main/java/project/global/config/S3Config.java
src/main/java/project/global/response/status/ErrorStatus.java
src/main/java/project/global/s3/service/S3Uploader.java

1. 리뷰 조회, 등록, 수정, 삭제 기능 구현
2. 이미지 저장을 위한 S3 연동
3. multi-part 데이터 요청 처리를 위해 application.yml에 아래 코드 추가
```yml
spring:
servlet:
multipart:
enabled: true
max-file-size: 10MB
max-request-size: 30MB
```
4. S3 연동을 위해 application.yml에 아래 코드 추가
```yml
cloud:
cloud:
aws:
credentials:
access-key: <문의 바람>
secret-key: <문의 바람>
region:
static: ap-northeast-2
s3:
bucket: pium-image-bucket
stack:
auto: false
```
Resolves: #25 
> 
> ![image](https://github.com/user-attachments/assets/317150b0-457a-48b5-a1f9-d2f5c688a0d8)
> ![image](https://github.com/user-attachments/assets/23772da9-da16-4363-8703-54ad0b15339a)
> [!NOTE]
> 이미지 데이터는 꼭 보내줘야하고, 사진에서와 같이 type(new, exist)를 꼭 설정해줘야 함. 그리고 type이 new인 경우에는 file, exist인 경우에는 url로 키값을 …

[FSE-42 FEAT] 리뷰 기능 구현

---

src/main/java/project/domain/cart/Cart.java
src/main/java/project/domain/cart/controller/CartController.java
src/main/java/project/domain/cart/dto/CartConverter.java
src/main/java/project/domain/cart/dto/CartResponse.java
src/main/java/project/domain/cart/service/CartService.java
src/main/java/project/domain/category/Category.java
src/main/java/project/domain/company/Company.java
src/main/java/project/domain/item/Item.java
src/main/java/project/domain/itemimage/ItemImage.java
src/main/java/project/domain/itemimage/enums/ImageType.java
src/main/java/project/domain/itemimage/repository/ItemImageRepository.java
src/main/java/project/domain/reviewimage/ReviewImage.java
src/main/java/project/domain/wishlist/controller/WishListController.java
src/main/java/project/domain/wishlist/dto/WishListConverter.java
src/main/java/project/domain/wishlist/dto/WishListResponse.java
src/main/java/project/domain/wishlist/repository/WishlistRepository.java
src/main/java/project/domain/wishlist/service/WishListService.java
src/main/java/project/global/config/S3Config.java
src/main/java/project/global/util/ImageUtil.java

- 찜,장바구니 관련 DTO에 아이템 이미지 추가 및 관련 서비스 코드 수정
Resolves: #29 
```java
```
> 
> 
>

[FEAT] 찜,장바구니 관련 DTO에 아이템 이미지 추가 및 관련 서비스 코드 수정

---

src/main/java/project/domain/member/Member.java
src/main/java/project/domain/member/controller/MemberController.java
src/main/java/project/domain/member/service/MemberService.java
src/main/java/project/domain/review/service/ReviewService.java
src/main/java/project/global/s3/util/S3Uploader.java

1. 사용자의 프로필사진 수정 기능을 구현했습니다.
#Resolves : #34
>
```java
```
> 
> 
>

[FEAT-34] : 사용자 프로필 사진 수정 기능 추가

---

src/main/java/project/domain/mbti/SkinAxis.java
src/main/java/project/domain/mbti/Step.java
src/main/java/project/domain/member/Member.java
src/main/java/project/domain/member/controller/MemberController.java
src/main/java/project/domain/member/dto/MemberConverter.java
src/main/java/project/domain/member/dto/MemberRequest.java
src/main/java/project/domain/member/dto/MemberResponse.java
src/main/java/project/domain/member/service/MemberService.java
src/main/java/project/global/enums/skin/SkinType.java

> 회원 탈퇴 기능을 추가했습니다.
```java
@Transactional
public ApiResponse<Boolean> deleteMember(Member member) {
memberRepository.findById(member.getId())
.orElseThrow(() -> new GeneralException(ErrorStatus.MEMBER_NOT_FOUND_BY_ID));
memberRepository.deleteById(member.getId());
return ApiResponse.onSuccess(true);
}
```
> ### 회원탈퇴를 하는 로직
> 
> 
>

[FS2-64 FEAT] 회원탈퇴 기능 추가

---

src/main/java/project/domain/aisummary/repository/AiSummaryRepository.java
src/main/java/project/domain/cautionskintype/CautionSkinType.java
src/main/java/project/domain/containingredient/repository/containIngredientRepository.java
src/main/java/project/domain/graph/Graph.java
src/main/java/project/domain/graph/repository/GraphRepository.java
src/main/java/project/domain/ingredient/Ingredient.java
src/main/java/project/domain/ingredient/enums/Risk.java
src/main/java/project/domain/item/Item.java
src/main/java/project/domain/item/controller/ItemController.java
src/main/java/project/domain/item/dto/ItemConverter.java
src/main/java/project/domain/item/dto/ItemResponse.java
src/main/java/project/domain/item/service/ItemService.java
src/main/java/project/domain/wishlist/dto/WishListConverter.java
src/main/java/project/global/response/status/ErrorStatus.java

- 상세 페이지에서 필요한 데이터를 넘겨주는 API 구현
Resolves: #39 
```java
```
> ### 1. 상품 정보 조회
> <img width="1402" alt="상품정보조회" src="https://github.com/user-attachments/assets/6362e5c7-3b82-412b-ae14-8c59a673ecef" />
> ### 2. 그래프 데이터 조회
> <img width="1407" alt="그래프데이터조회" src="https://github.com/user-attachments/assets/45fe9f87-bd3d-4442-b37c-6954f9f3a46e" />
> ### 3. 민감주의 성분 조회
> <img width="1391" alt="민감주의성분조회" src="https://github.com/user-attachments/assets/61210133-3c9d-477d-ada3-2a93d7b45fcc" />
> ### 4. 성분스코어 개수 조회
> <img width="1395" alt="성분스코어개수조회" src="https://github.com/user-attachments/assets/29a6ceb5-5db9-4347-963d-dafce23ca164" />
> ### 5. 성분 스코어 조회
> <img …

[FS2-29 FEAT] 상품 상세페이지 관련 API 구현

---

src/main/java/project/domain/cart/controller/CartController.java
src/main/java/project/domain/cart/dto/CartConverter.java
src/main/java/project/domain/cart/dto/CartRequest.java
src/main/java/project/domain/cart/dto/CartResponse.java
src/main/java/project/domain/cart/service/CartService.java
src/main/java/project/domain/cartitem/CartItem.java
src/main/java/project/domain/cartitem/repository/CartItemRepository.java
src/main/java/project/domain/itemoption/repository/ItemOptionRepository.java

1. 장바구니에서 옵션도 조회되게 추가
2. 옵션 수정 추가
- 만약, 옵션 변경시 중복되는 아이템이 존재하는 경우 하나로 합쳐짐
3. 수량 감소할 때 개수가 0이 되면 장바구니에서 삭제됨
Resolves: #47 
```java
```
> ### 1. 장바구니 조회
> <img width="1405" alt="장바구니 등록 요청" src="https://github.com/user-attachments/assets/93065cac-21d1-49fb-8a7a-010aaeb42724" />
> <img width="1408" alt="장바구니 등록 응답" src="https://github.com/user-attachments/assets/cd49dfca-c39a-4026-bdf5-b0f84a0b3778" />
> ### 2. 장바구니 아이템 옵션 수정
> <img width="1413" alt="옵션 수정 요청" src="https://github.com/user-attachments/assets/ade4c088-80ba-4b1a-ad4e-388823312020" />
> <img width="1398" alt="옵션 수정 응답" src="https://github.com/user-attachments/assets/6a647c6f-7a60-4ef4-8a98-7e710c22fc05" />
> …

[FS2-66 FEAT] 장바구니 옵션 추가

---

src/main/java/project/domain/cart/controller/CartController.java
src/main/java/project/domain/cart/service/CartService.java
src/main/java/project/domain/cartitem/repository/CartItemRepository.java
src/main/java/project/domain/item/controller/ItemController.java
src/main/java/project/domain/item/controller/ItemSearchController.java
src/main/java/project/domain/item/dto/ItemConverter.java
src/main/java/project/domain/item/dto/ItemSearchConverter.java
src/main/java/project/domain/item/dto/ItemSearchResponse.java
src/main/java/project/domain/item/repository/ItemRepository.java
src/main/java/project/domain/item/service/ItemSearchService.java
src/main/java/project/domain/member/Member.java
src/main/java/project/domain/purchasehistory/PurchaseHistory.java

- 카테고리 별 상품 조회 및 검색 키워드에 따른 상품 조회 구현
- 비건 제품 조회 구현
- 결제 기능 구현
> 피부 고민 별 조회는 아직 데이터 만들기 전이여서 추후에 구현 예정입니다.
Resolves: #49 
```java
```
> ### 1. 서브 카테고리 별 상품 조회
> <img width="1393" alt="서브카테고리 상품 조회 요청" src="https://github.com/user-attachments/assets/515ad82f-499b-4e88-8b7a-e51540558485" />
> <img width="1399" alt="서브카테고리 상품 조회 응답" src="https://github.com/user-attachments/assets/69c02aa7-cea9-4cd1-99e5-707e175d9ccc" />
> ### 2. 검색 키워드 상품 조회
> <img width="1407" alt="검색 키워드 상품 조회 요청" src="https://github.com/user-attachments/assets/c6ab6051-1abb-4231-b271-bb690a6d0e80" />
> <img width="1398" alt="검색 키워드 상품 조회 응답" src="https://github.com/user-attachments/assets/14959855-ee79-40d7-be96-7deeb29 …

[FS2-67 FEAT] 카테고리 별 상품 조회 및 검색 키워드에 따른 상품 조회 구현

---

src/main/java/project/domain/purchasehistory/PurchaseHistory.java
src/main/java/project/domain/purchasehistory/dto/PurchaseHistoryConverter.java
src/main/java/project/domain/purchasehistory/dto/PurchaseHistoryResponse.java

1. 상세보기에 할인율을 추가하였습니다.
Resolves : #55
>

[FCS-69 FIX] : 구매내역 조회 기능 수정

---

src/main/java/project/domain/mbti/SkinAxis.java
src/main/java/project/domain/mbti/Step.java
src/main/java/project/domain/member/Member.java
src/main/java/project/domain/member/dto/MemberConverter.java
src/main/java/project/global/enums/skin/AxisType.java

[FIX 62] 축관련 타입 enum 분리

---

src/main/java/project/domain/aisummary/AiSummary.java
src/main/java/project/domain/item/dto/ItemConverter.java
src/main/java/project/domain/item/dto/ItemResponse.java

- AI 요약 테이블에 아이템 옵션 필드 추가
Resolves: #73 
```java
```
> 
> 
>

[FS2-82 FEAT] AI 요약 테이블 아이템 옵션 필드 추가

---

.github/workflows/deploy.yml
build.gradle

[FEAT] CI/CD 추가

---

build.gradle
src/main/java/project/domain/item/controller/ItemSearchController.java
src/main/java/project/domain/item/dto/ItemSearchConverter.java
src/main/java/project/domain/item/dto/ItemSearchResponse.java
src/main/java/project/domain/item/repository/ItemDynamicSort.java
src/main/java/project/domain/item/repository/ItemRepository.java
src/main/java/project/domain/item/service/ItemSearchService.java
src/main/java/project/domain/review/Review.java
src/main/java/project/global/config/QueryDSLConfig.java
src/main/resources/logback-spring.xml

- 피부 고민별 상품 조회되게 수정
- 클라이언트에서 가상스크롤로 구현하기 위해 페이지네이션 형태가 아닌 전체 데이터를 전송하는 방식으로 수정
> 쿼리파라미터로 페이지값 넘겨주지 않아도됨
- 가격순, 별점순으로 정렬되게 정렬 옵션 추가
> 쿼리 파라미터의 유무와 값에 따라 쿼리 옵션이 동적으로 바뀌기 때문에 아래와 같이 QueryDSL을 활용하여 코드 효율성과 가독성을 높임
> 쿼리 파라미터로 priceSort 값을 넘겨주면됨 -> 안넘겨주면 - 별점순, PRICE_ASC - 낮은 가격순, PRICE_DESC - 높은 가격순
> 만약, 피부 고민이 설정되어있으면 기본 정렬이 별점순이 아닌 Item_score순으로 정렬
```java
package project.domain.item.repository;
import com.querydsl.jpa.impl.JPAQuery;
import com.querydsl.jpa.impl.JPAQueryFactory;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Repository;
import org.springframework.util.StringUtils;
import project.domain.item.Item;
import project.domain.item.QItem;
import project.domain.item.enums.VeganType;
import project.domain.itemimage.QItemImage;
import …
```

[FS2-83 FEAT] 피부 고민별 상품 조회

---

src/main/java/project/domain/item/controller/ItemRecommendController.java
src/main/java/project/domain/item/controller/ItemSearchController.java
src/main/java/project/domain/item/dto/ItemSearchResponse.java
src/main/java/project/domain/item/dto/converter/ItemConverter.java
src/main/java/project/domain/item/dto/converter/ItemRecommendConverter.java
src/main/java/project/domain/item/dto/converter/ItemSearchConverter.java
src/main/java/project/domain/item/service/ItemRecommendService.java
src/main/java/project/domain/item/service/ItemSearchService.java
src/main/java/project/domain/item/service/ItemService.java
src/main/java/project/domain/trenditem/TrendItem.java
src/main/java/project/domain/trenditem/dto/TrendItemConverter.java
src/main/java/project/domain/trenditem/dto/TrendItemDTO.java
src/main/java/project/domain/trenditem/repository/TrendItemRepository.java
src/main/java/project/global/redis/controller/RedisController.java
src/main/java/project/global/redis/dto/ItemViewScoreDTO.java
src/main/java/project/global/redis/service/ItemViewRedis.java
src/main/java/project/global/redis/service/popular/PopularCacheService.java
src/main/java/project/global/redis/service/popular/PopularItemsBatchService.java
src/main/java/project/global/redis/service/trend/TrendCacheService.java
src/main/java/project/global/redis/service/trend/TrendItemBatchService.java

>
- 인기 급상승 제품 Top10 조회 구현
- 최근 3시간 동안의 시간당 조회수에 가중치(1, 0.7, 0.5)를 다르게 곱하여 얻은 점수로 선별
- 상품 추천 관련 API들을 별도 파일로 관리하도록 변경 (item/ItemRecommend~)
Resolves: #88 
```java
```
> 
> 
>

[FEAT] 인기 급상승 제품 Top10 조회

---

src/main/java/project/domain/itemimage/repository/ItemImageRepository.java
src/main/java/project/global/chat/controller/ChatController.java
src/main/java/project/global/chat/dto/ChatResponseDTO.java
src/main/java/project/global/chat/service/ChatService.java

```java
@RequiredArgsConstructor
@Service
public class ChatService {
private final WebClient webClient = WebClient.create("http://52.79.241.142:8000");
private final ItemImageRepository itemImageRepository;
public Mono<ChatResponseDTO> sendToFastApi(ChatRequestDTO request, Member member) {
request.setSession_id(member.getId().toString());
return webClient.post()
.uri("http://52.79.241.142:8000/chat")
.bodyValue(request)
.retrieve()
.bodyToMono(ChatResponseDTO.class);
}
public ChatResponseDTO getImgUrl(ChatResponseDTO request) {
request.getItemList().forEach(item -> {
itemImageRepository.findFirstByItemIdAndImageType(item.getItemId(), ImageType.MAIN)
.ifPresentOrElse(
image -> item.setImgUrl(image.getUrl()),
() -> item.setImgUrl(null)
);
});
return request;
}
}
```
> 리뷰어가 특별히 봐주었으면 하는 부분이 …

[FIX-83] : 챗봇 기능 수정

---

src/main/java/project/domain/areapopularitem/repository/AreaPopularItemRepository.java
src/main/java/project/domain/item/controller/ItemRecommendController.java
src/main/java/project/domain/item/dto/ItemRecommendResponse.java
src/main/java/project/domain/item/dto/converter/ItemRecommendConverter.java
src/main/java/project/domain/item/service/ItemRecommendService.java
src/main/java/project/domain/member/Member.java
src/main/java/project/domain/member/repository/MemberRepository.java
src/main/java/project/domain/relatedpurchaseitem/RelatedPurchaseItem.java
src/main/java/project/domain/relatedpurchaseitem/repository/RelatedPurchaseItemRepository.java
src/main/java/project/domain/relatedviewitem/RelatedViewItem.java
src/main/java/project/domain/relatedviewitem/repository/RelatedViewItemRepository.java

>
- ML에서 만든 데이터 서빙 API 구현
Resolves: #97 
```java
```
> 
> 
>

[FEAT] ML에서 만든 데이터 서빙 API 구현
